# Generated by Django 4.2.1 on 2023-06-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=255)),
                ('animal', models.CharField(max_length=255)),
                ('idade', models.IntegerField()),
                ('servico', models.CharField(max_length=255)),
                ('valor', models.FloatField()),
                ('pagamento', models.CharField(max_length=255)),
            ],
        ),
    ]
